### ISSUE TITLE
Warlords of Draenor Intro not auto-selected from callboard anymore

### ISSUE THREAD

**Issue by KrakenLatte** [Saaappi/HelpMePlay#13]
Warlords of Draenor Intro quest is not being auto-selected from the callboard anymore.

**Comment by Saaappi** [comment]
@KrakenLatte I was unable to replicate this problem on a fresh character from Exile's Reach. Are you able to recall your exact character conditions under which you experienced this bug?

Details such as character level, the zone you were in, and whether or not Tanaan Jungle was one of the three first options would all be helpful.

Thanks!

**Comment by Saaappi** [comment]
Addressed with 99dfce5.
