### ISSUE TITLE
Learn Transmog button missing with ElvUI bags enabled

### ISSUE THREAD

**Issue by Pairaka** [Saaappi/HelpMePlay#15]
Transmog button is not visible with ElvUI bags enabled. 

ElvUI bags disabled, default bags. Learn Transmog button visible: 
![WoWScrnShot_110322_083428](https://user-images.githubusercontent.com/39540618/199722059-470529ae-e2c6-4e9d-b8f2-b2e9eeffc933.jpg)

ElvUI bags enabled. Learn Transmog button is not visible: 
![WoWScrnShot_110322_083502](https://user-images.githubusercontent.com/39540618/199722287-96b3cab7-cd15-4388-b7b2-7d22ead7aaed.jpg)

**Comment by Saaappi** [comment]
Fixed in 93d3e22.
