### ISSUE TITLE
Requesting Action Bar Profiles Saver absorption? :D

### ISSUE THREAD

**Issue by KrakenLatte** [Saaappi/HelpMePlay#22]
Action Bar Profiles (Saver) still has not be picked up and the alternatives are not great because they are not very user friendly (just want a couple buttons to click and be done, you know?). Requesting this be added into HMP if possible OR at least have the og addon repaired! Totally understand if it's too complex. The features I would be requesting are:

Class specific profiles that are shared account-wide and include:
1. keybinds
2. macros (especially the character specific ones!)
3. ability AND macro placement on actionbars (other addons are bad about the macros half)
4. option to make specific profiles (ABP had it as class based, and then you make your specs for each class-- this was perfect for multiple builds!)
5. talents (IF possible. The new talent loadouts don't work great if you import them before you are max level. They won't update to add the new talents you have saved as you level and you have to REIMPORT the whole thing AFTER leveling! What's the point!)

Thank you and I love you. Still serious about that Patreon if you decide to make one. I would hands-down donate to keep these alive!

**Comment by Saaappi** [comment]
No need to implement. Kraken found an update for ABP.

https://cdn.discordapp.com/attachments/968857343276245032/1044855035634405427/wow-action-bar-profiles-master.zip
