### ISSUE TITLE
Requesting quest button option like New Openables!

### ISSUE THREAD

**Issue by KrakenLatte** [Saaappi/HelpMePlay#23]
The New Openables addon may be officially abandoned! While it was great for opening openables, the feature I liked most was adding a movable extra button that would pop up for quests that have quest items (ex: using the bug spray on drogbar in Highmountain). I could position and enlarge this button above my action bars so it was like the special/extra action button that pops up for special abililties, but for quest items! AND I could keybind it! The ones that show up next to the objective list (thanks to other addons) just aren't very useful.

**Comment by Saaappi** [comment]
Someone picked up the New Openables addon.
