### ISSUE TITLE
HelpMePlay Junker lua error everytime I mouseover gear even though Junk is disabled

### ISSUE THREAD

**Issue by KrakenLatte** [Saaappi/HelpMePlay#24]
Message: Interface/AddOns/HelpMePlay/Systems/Junker.lua:177: attempt to call method 'GetItem' (a nil value)
Time: Mon Nov 21 20:54:15 2022
Count: 39
Stack: Interface/AddOns/HelpMePlay/Systems/Junker.lua:177: attempt to call method 'GetItem' (a nil value)
[string "=[C]"]: in function `GetItem'
[string "@Interface/AddOns/HelpMePlay/Systems/Junker.lua"]:177: in function <Interface/AddOns/HelpMePlay/Systems/Junker.lua:175>
[string "=(tail call)"]: ?
[string "=[C]"]: in function `securecallfunction'
[string "@Interface/SharedXML/Tooltip/TooltipDataHandler.lua"]:60: in function <Interface/SharedXML/Tooltip/TooltipDataHandler.lua:55>
[string "@Interface/SharedXML/Tooltip/TooltipDataHandler.lua"]:80: in function <Interface/SharedXML/Tooltip/TooltipDataHandler.lua:76>
[string "@Interface/SharedXML/Tooltip/TooltipDataHandler.lua"]:116: in function <Interface/SharedXML/Tooltip/TooltipDataHandler.lua:106>
[string "=[C]"]: in function `SetAttribute'
[string "@Interface/SharedXML/Tooltip/TooltipDataHandler.lua"]:141: in function <Interface/SharedXML/Tooltip/TooltipDataHandler.lua:134>
[string "@Interface/SharedXML/Tooltip/TooltipDataHandler.lua"]:282: in function <Interface/SharedXML/Tooltip/TooltipDataHandler.lua:240>
[string "=[C]"]: in function `securecallfunction'
[string "@Interface/SharedXML/Tooltip/TooltipDataHandler.lua"]:237: in function `ProcessInfo'
[string "@Interface/SharedXML/Tooltip/TooltipComparisonManager.lua"]:249: in function `SetItemTooltip'
[string "@Interface/SharedXML/Tooltip/TooltipComparisonManager.lua"]:168: in function `RefreshItems'
[string "@Interface/SharedXML/Tooltip/TooltipComparisonManager.lua"]:158: in function `CompareItem'
[string "@Interface/FrameXML/GameTooltip.lua"]:527: in function `GameTooltip_ShowCompareItem'
[string "@Interface/FrameXML/ContainerFrame.lua"]:1507: in function `ContainerFrameItemButton_OnEnter'
[string "@Interface/AddOns/Bagnon/common/Wildpants/classes/item.lua"]:352: in function `UpdateTooltip'
[string "@Interface/AddOns/Bagnon/common/Wildpants/classes/item.lua"]:184: in function <...face/AddOns/Bagnon/common/Wildpants/classes/item.lua:179>

Locals:

**Comment by Saaappi** [comment]
Fixed in ca24d1b and 4a56af4.
