### ISSUE TITLE
Learn All Transmog button remaining when bags are closed (with ElvUI bags enabled)

### ISSUE THREAD

**Issue by Pairaka** [Saaappi/HelpMePlay#27]
See screenshots. Sometimes the Learn All Transmog button remains when bags are closed. This behavior is inconsistent: sometimes it disappears when bags are closed; sometimes it clears like it's supposed to. I've noticed that it stays around for a few moments after bags are closed, then will clear. 

(Also of note: If I disable ElvUI bags, the Transmog button is not there. If I disable ElvUI completely, the Transmog button appears like it should.) 

> 9x HelpMePlay/Systems/Transmog.lua:154: attempt to index global 'ElvUI_ContainerFrame' (a nil value)
> [string "@HelpMePlay/Systems/Transmog.lua"]:154: in function <HelpMePlay/Systems/Transmog.lua:152>
> 
> Locals:
> (*temporary) = nil
> (*temporary) = nil
> (*temporary) = "TOPRIGHT"
> (*temporary) = nil
> (*temporary) = "TOPLEFT"
> (*temporary) = -5
> (*temporary) = -1
> (*temporary) = "attempt to index global 'ElvUI_ContainerFrame' (a nil value)"
> HMPTransmogButton = HMPTransmogButton {
>  SetTextToFit = <function> defined @SharedXML/SecureUIPanelTemplates.lua:440
>  Right = Texture {
>  }
>  Left = Texture {
>  }
>  fitTextWidthPadding = 40
>  FitToText = <function> defined @SharedXML/SecureUIPanelTemplates.lua:445
>  Text = HMPTransmogButtonText {
>  }
>  0 = <userdata>
>  Middle = Texture {
>  }
>  fitTextCanWidthDecrease = true
> }

![WoWScrnShot_112422_111455](https://user-images.githubusercontent.com/39540618/203831087-0699302b-aab7-48b9-b91d-1d16b67cf91f.jpg)

![WoWScrnShot_112422_111430](https://user-images.githubusercontent.com/39540618/203831017-f0722142-1e86-4ed6-876e-3f657eebb056.jpg)

**Comment by Pairaka** [comment]
Some added info on this behavior: If I use the keybind to close my bags ('B'), the button goes away. If I use the ESC key, the button remains.

**Comment by Saaappi** [comment]
Fixed in 81b480a.
