### ISSUE TITLE
Transmog button does not work with ElvUI

### ISSUE THREAD

**Issue by Pairaka** [Saaappi/HelpMePlay#28]
Have learnable items in my bags, use the Transmog button and nothing happens (with ElvUI bags enabled). Got this error: 

2x HelpMePlay/Systems/Transmog.lua:42: attempt to call global 'GetContainerNumSlots' (a nil value)
[string "@HelpMePlay/Systems/Transmog.lua"]:42: in function <HelpMePlay/Systems/Transmog.lua:40>

Locals:
(for index) = 0
(for limit) = 4
(for step) = 1
i = 0
(*temporary) = 1
(*temporary) = nil
(*temporary) = 0
(*temporary) = "attempt to call global 'GetContainerNumSlots' (a nil value)"
RequipOriginalItems = <function> defined @HelpMePlay/Systems/Transmog.lua:15
equippedItems = <table> {
 1 = <table> {
 }
 2 = <table> {
 }
 3 = <table> {
 }
 4 = <table> {
 }
 5 = <table> {
 }
 6 = <table> {
 }
 7 = <table> {
 }
 8 = <table> {
 }
 9 = <table> {
 }
 10 = <table> {
 }
 11 = <table> {
 }
 12 = <table> {
 }
}

**Comment by Pairaka** [comment]
Related to this issue: Disabling ElvUI bags causes the Transmog button to not show at all, and gives this error: 

1x HelpMePlay/Systems/Transmog.lua:154: attempt to index global 'ElvUI_ContainerFrame' (a nil value)
[string "@HelpMePlay/Systems/Transmog.lua"]:154: in function <HelpMePlay/Systems/Transmog.lua:152>

Locals:
(*temporary) = nil
(*temporary) = nil
(*temporary) = "TOPRIGHT"
(*temporary) = nil
(*temporary) = "TOPLEFT"
(*temporary) = -5
(*temporary) = -1
(*temporary) = "attempt to index global 'ElvUI_ContainerFrame' (a nil value)"
HMPTransmogButton = HMPTransmogButton {
 SetTextToFit = <function> defined @SharedXML/SecureUIPanelTemplates.lua:440
 Right = Texture {
 }
 Left = Texture {
 }
 fitTextWidthPadding = 40
 FitToText = <function> defined @SharedXML/SecureUIPanelTemplates.lua:445
 Text = HMPTransmogButtonText {
 }
 0 = <userdata>
 Middle = Texture {
 }
 fitTextCanWidthDecrease = true
}

**Comment by Saaappi** [comment]
The second error is technically a different problem. I've opened a separate issue for it.

**Comment by Saaappi** [comment]
The first error is fixed in 20f2ebf.
