### ISSUE TITLE
Learn All Transmog button?

### ISSUE THREAD

**Issue by joeyherne** [Saaappi/HelpMePlay#34]
The "Learn All Transmog" button has been added by the Help Me Play addon with no option to move or disable it. Why would I want a permament button on my screen to blanket soulbind all of my BOEs that I'm trying to sell? If there is a way to fix it with current version please let me know.

**Comment by Saaappi** [comment]
@joeyherne I'll add the option for players to disable the button.

**Comment by Saaappi** [comment]
Added in cf8fdad.
