### ISSUE TITLE
Transmog Button not operating as expected

### ISSUE THREAD

**Issue by Erieeroot** [Saaappi/HelpMePlay#35]
Pressing button to learn transmog produces the character sheet 2x, then nothing.  No errors are produced.    

Fresh install of addon
No other addons loaded
10.0.2 Retail 
HMP v.2.0.6

**Comment by Erieeroot** [comment]
![transmog](https://user-images.githubusercontent.com/71171107/204645286-d57d164b-3562-453d-92b2-787a3c423367.png)

4 items in inventory that are not yet known.

**Comment by Saaappi** [comment]
Thank you for the report. I'll investigate and get this fixed for 2.0.7. (No ETA on release.)

**Comment by Saaappi** [comment]
Fixed in ebc9660.
