### ISSUE TITLE
Requesting faction-specific BFA intro toggle

### ISSUE THREAD

**Issue by KrakenLatte** [Saaappi/HelpMePlay#38]
Is there anyway you can add another or different setting to HMP that's faction-based for the BFA intro? I have to keep changing my setting since I prefer to do it on Alliance (if I'm leveling) but Horde always skips because their scenario doesn't give xp.
Like even just having two of those (whatever's easier) checkboxes would be fine. Doesn't have to be fancy. I just have to remember to check it every time I swap factions XD

**Comment by Saaappi** [comment]
Updated in 241ba68.
