### ISSUE TITLE
attempt to index global 'HelpMePlayOptionsDB' (a nil value) / attempt to index global 'HelpMePlayJunkerGlobalDB' (a nil value)

### ISSUE THREAD

**Issue by Quartzfire** [Saaappi/HelpMePlay#45]
Get this LUA, immediately followed by the one below.

This happens at login, but also if I open bags and mouse over things, like hearthstone.

Junker is not enabled.

3x HelpMePlay/HelpMePlay.lua:75: attempt to index global 'HelpMePlayOptionsDB' (a nil value)
[string "@HelpMePlay/HelpMePlay.lua"]:75: in function <HelpMePlay/HelpMePlay.lua:55>

Locals:
self = Frame {
0 =
}
event = "ADDON_LOADED"
addonLoaded = "HelpMePlay"
(*temporary) = nil
(*temporary) =

{
}
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index global 'HelpMePlayOptionsDB' (a nil value)"
addonName = "HelpMePlay"

====================================================================

169x HelpMePlay/Systems/Junker.lua:181: attempt to index global 'HelpMePlayJunkerGlobalDB' (a nil value)
[string "@HelpMePlay/Systems/Junker.lua"]:181: in function <HelpMePlay/Systems/Junker.lua:175>
[string "=(tail call)"]: ?
[string "=[C]"]: in function `securecallfunction'
[string "@SharedXML/Tooltip/TooltipDataHandler.lua"]:60: in function <SharedXML/Tooltip/TooltipDataHandler.lua:55>
[string "@SharedXML/Tooltip/TooltipDataHandler.lua"]:80: in function <SharedXML/Tooltip/TooltipDataHandler.lua:76>
[string "@SharedXML/Tooltip/TooltipDataHandler.lua"]:116: in function <SharedXML/Tooltip/TooltipDataHandler.lua:106>
[string "=[C]"]: in function `SetAttribute'
[string "@SharedXML/Tooltip/TooltipDataHandler.lua"]:141: in function <SharedXML/Tooltip/TooltipDataHandler.lua:134>
[string "@SharedXML/Tooltip/TooltipDataHandler.lua"]:282: in function <SharedXML/Tooltip/TooltipDataHandler.lua:240>
[string "=[C]"]: in function `securecallfunction'
[string "@SharedXML/Tooltip/TooltipDataHandler.lua"]:237: in function <SharedXML/Tooltip/TooltipDataHandler.lua:236>
[string "=(tail call)"]: ?
[string "@Pawn/Pawn.lua"]:2083: in function `PawnGetStatsFromTooltipWithMethod'
[string "@Pawn/Pawn.lua"]:1325: in function `PawnGetItemData'
[string "@Pawn/Pawn.lua"]:1565: in function `PawnGetItemDataForInventorySlot'
[string "@Pawn/Pawn.lua"]:3784: in function `PawnCheckInventoryForUpgrades'
[string "@Pawn/Pawn.lua"]:4077: in function <Pawn/Pawn.lua:4069>
[string "@Pawn/VgerCore/VgerCore.lua"]:353: in function `PawnOnInventoryChanged'
[string "@Pawn/Pawn.lua"]:126: in function `PawnOnEvent'
[string "*PawnUI.xml:1653_OnEvent"]:1: in function <[string "*PawnUI.xml:1653_OnEvent"]:1>

Locals:
tooltip = PawnPrivateTooltip1 {
 0 = <userdata>
 SetQuestLogRewardSpell = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetQuestPartyProgress = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 ProcessLineData = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:303
 SetPvpTalent = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetRuneforgeResultItem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetHyperlink = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetUnit = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetAzeriteEssence = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetVoidDepositItem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetVoidWithdrawalItem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 CIMI_tooltipWritten = true
 AttachComplete = true
 SetPetAction = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetInfoBackdropStyle = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:338
 AllTheThingsProcessing = "|cffa335ee|Hitem:190360::::::::60:253::11:5:8109:7955:6652:7579:1472:1:28:2057:::::|h[Enigmatic Cowl]|h|r"
 hasMoney = 1
 SetSocketGem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 shownMoneyFrames = 1
 numMoneyFrames = 1
 info = <table> {
 }
 SetLootCurrency = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetSlottedKeystone = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetWorldCursor = <function> defined @FrameXML/GameTooltip.lua:952
 SetLootItem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 StatusBar = PawnPrivateTooltip1StatusBar {
 }
 GetUnit = <function> defined @FrameXML/GameTooltip.lua:994
 SetOwnedItemByID = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetMerchantCostItem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetQuestLogSpecialItem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetItemInteractionItem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 TextRight1 = PawnPrivateTooltip1TextRight1 {
 }
 SetRecipeReagentItem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetQuestCurrency = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetEnhancedConduit = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetWeeklyReward = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetMerchantItem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetPvpBrawl = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetAchievementByID = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 BottomOverlay = Texture {
 }
 SetSpellByID = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 supportsDataRefresh = true
 SetSocketedRelic = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 ProcessInfo = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:236
 ProcessLines = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:293
 NineSlice = Frame {
 }
 SetInventoryItem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 RefreshData = <function> defined @FrameXML/GameTooltip.lua:933
 SetTransmogrifyItem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetLootRollItem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 OnLoad = <function> defined @FrameXML/GameTooltip.lua:927
 SetQuestLogCurrency = <function> defined @SharedXML/Tooltip/TooltipDataH

**Comment by Quartzfire** [comment]
Before the above I get this:

3x HelpMePlay/HelpMePlay.lua:75: attempt to index global 'HelpMePlayOptionsDB' (a nil value)
[string "@HelpMePlay/HelpMePlay.lua"]:75: in function <HelpMePlay/HelpMePlay.lua:55>

Locals:
self = Frame {
 0 = <userdata>
}
event = "ADDON_LOADED"
addonLoaded = "HelpMePlay"
(*temporary) = nil
(*temporary) = <table> {
}
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index global 'HelpMePlayOptionsDB' (a nil value)"
addonName = "HelpMePlay"

**Comment by Saaappi** [comment]
@Quartzfire The top error is the culprit, the bottom one is caused by the first. I fixed the top error in cc567d6.

Thank you for the report.
