### ISSUE TITLE
As a User, I want the Torghast Anima Powers automation to work with Patch 10.0.2

### ISSUE THREAD

**Issue by Loreinator** [Saaappi/HelpMePlay#48]
When enabling the Torghast anima powers automation in Patch 10.0.2, an error is produced when an anima power choice appears, and it doesn't choose one for me or suggest one. I tried it with both Notify and No Epics (Automatic).

Message: ...erface/AddOns/HelpMePlay/Automations/AnimaPowers.lua:130: attempt to call field 'GetPlayerChoiceInfo' (a nil value)
Time: Thu Dec 29 22:29:04 2022
Count: 10
Stack: ...erface/AddOns/HelpMePlay/Automations/AnimaPowers.lua:130: attempt to call field 'GetPlayerChoiceInfo' (a nil value)
[string "=[tsm error check]"]:1: in main chunk
[string "=(tail call)"]: ?
[string "=[C]"]: in function `GetPlayerChoiceInfo'
[string "@Interface/AddOns/HelpMePlay/Automations/AnimaPowers.lua"]:130: in function <...erface/AddOns/HelpMePlay/Automations/AnimaPowers.lua:24>

Locals:

**Comment by Saaappi** [comment]
Thank you for the report. I haven't returned to Torghast since probably March-April-ish.

10.0 changed the player choice API, so I'll get this fixed for the next update.

**Comment by Saaappi** [comment]
@Loreinator Can you tell me what version of HelpMePlay you're on?

**Comment by Loreinator** [comment]
2.0.7

**Comment by Saaappi** [comment]
Fixed for the next update, @Loreinator .
