### ISSUE TITLE
Feature Request: Automate Learning Dragonriding Abilities

### ISSUE THREAD

**Issue by eTzmNcbkrng** [Saaappi/HelpMePlay#49]
Dragonriding Glyphs are account-wide, but spending them is not. Spending the Glyphs on the various talents is ttedious as you have to click and confirm each one.

Would appreciate some logic that checks if I have unlocked all 48 Glyphs and if so automatically learns all the abilities.

Thanks.

**Comment by Saaappi** [comment]
@eTzmNcbkrng This is already a feature in 2.0.7. Go into the Options, select the General tab, check the Dragonriding Button toggle, reload your UI, then all your characters will have a "Learn" button in the Dragonriding UI for quickly learning all its talents.

**Comment by eTzmNcbkrng** [comment]
My bad, thanks for this. I now see that WoWUp isn't detecting releases on the GitHub repo so I had to manually update.
