### ISSUE TITLE
Lua Error on NPC  Mouseover in Ardenweald

### ISSUE THREAD

**Issue by eivl** [Saaappi/HelpMePlay#5]
```
Message: Interface\AddOns\HelpMePlay\Mouseover.lua:153: attempt to index field '?' (a nil value)
Time: Sun May  1 11:57:12 2022
Count: 26
Stack: Interface\AddOns\HelpMePlay\Mouseover.lua:153: attempt to index field '?' (a nil value)
[string "=[C]"]: ?
[string "@Interface\AddOns\HelpMePlay\Mouseover.lua"]:153: in function <Interface\AddOns\HelpMePlay\Mouseover.lua:117>

Locals:
```

NPC: Lady of the Falls https://www.wowhead.com/npc=158345/lady-of-the-falls

PS: this happened more the once for different NPCs, but I forgot to record those details. 

EDIT: HMP version 1.0.9

**Comment by Saaappi** [comment]
@eivl Please upgrade. I shifted the project from CurseForge to [Wago](https://addons.wago.io/addons/helpmeplay). 1.0.9 is roughly 3 months old.

If you still have the problem on 1.1.6a, please come back and let me know. If I don't hear from you, or the issue doesn't persist, we'll close this issue.

**Comment by eivl** [comment]
i did not catch that, the issue is gone with the latest version `1.1.6a`

I have installed the Wago app and will have it update the addon for me. :D
