### ISSUE TITLE
As a player, I expect not to see an error when selecting an enemy in the Ascension Coliseum

### ISSUE THREAD

**Issue by Loreinator** [Saaappi/HelpMePlay#53]
When I click on the Soul Mirror within the Ascension Coliseum (Kyrian covenant feature), I get an error message:

Message: ...rface/AddOns/HelpMePlay/Automations/PlayerChoice.lua:31: bad argument #2 to 'split' (string expected, got nil)
Time: Sat Jan  7 17:20:03 2023
Count: 4
Stack: ...rface/AddOns/HelpMePlay/Automations/PlayerChoice.lua:31: bad argument #2 to 'split' (string expected, got nil)
[string "=[tsm error check]"]:1: in main chunk
[string "=(tail call)"]: ?
[string "=[C]"]: ?
[string "=[C]"]: in function `split'
[string "@Interface/AddOns/HelpMePlay/Automations/PlayerChoice.lua"]:31: in function <...rface/AddOns/HelpMePlay/Automations/PlayerChoice.lua:24>

Locals: 

I'm currently running 2.0.7, and just freshly joined Kyrian (first time going in there).

**Comment by Saaappi** [comment]
Interesting. I'll check it out today.

**Comment by Saaappi** [comment]
@Loreinator By chance did you have something targeted while interacting with the Soul Mirror? The Soul Mirror isn't even an NPC, nor does it fire the PlayerChoice code (at least not on my end).

**Comment by Loreinator** [comment]
Nothing targeted; it just pops the error every time I click the soul mirror, then choose an option. So far, it occurs with: Kalisthene, Echthra, and Alderyn and Myn'ir (I've just unlocked those ones, and it happens with them too).

**Comment by Saaappi** [comment]
Okay. I'll hold this open until after 2.0.8. If the issue persists post-update (no ETA), let me know. :)

**Comment by Loreinator** [comment]
I just tested it with the public-test branch's contents (current 2.0.8), and the same error still comes up as soon as you choose something in the dialog of the soul mirror. Both with and without something targeted, the same error appears. I also tried with every other addon disabled (literally only HelpMePlay enabled), and the same error appears.

**Comment by Saaappi** [comment]
Ah, so it's when you _choose_ an option. Okay, let me test that then.

**Comment by Saaappi** [comment]
Fixed.

**Comment by Loreinator** [comment]
Confirmed, no more errors now 👍
