### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by Spydawg** [Saaappi/HelpMePlay#56]
5x HelpMePlay/HelpMePlay.lua:57: attempt to compare number with nil
[string "@HelpMePlay/HelpMePlay.lua"]:57: in function <HelpMePlay/HelpMePlay.lua:9>
[string "=[C]"]: ?
[string "@Ace3/AceAddon-3.0-13/AceAddon-3.0.lua"]:66: in function <Ace3/AceAddon-3.0/AceAddon-3.0.lua:61>
[string "@Ace3/AceAddon-3.0-13/AceAddon-3.0.lua"]:494: in function `InitializeAddon'
[string "@Ace3/AceAddon-3.0-13/AceAddon-3.0.lua"]:619: in function <Ace3/AceAddon-3.0/AceAddon-3.0.lua:611>

**Comment by Saaappi** [comment]
Go into the settings and adjust the Torghast Powers automation under Expansion Features. That will make it go away, but I'll push an update in the next day or two.
