### ISSUE TITLE
Cinematic cancelling option too slow!

### ISSUE THREAD

**Issue by KrakenLatte** [Saaappi/HelpMePlay#6]
HMP seems to be skipping cinematics very slowly. Like it takes a few seconds to kick in instead of cancelling the cinematics before they start like it used to. You'd mentioned this is on purpose to prevent tainting, so is there a way to make it like, a second or two shorter at least? I've been able to cancel the cinematics on my own faster than poor HMP can! XD

Either way, tysm for all your hard work on this glorious addon. <3

**Comment by Saaappi** [comment]
![image](https://user-images.githubusercontent.com/36806900/183808407-f2797e96-b5b7-4a47-b8b9-8d973dfb9e61.png)

I reduced the top timer to 1s (down from 1.5s). The second timer was reduced to 1.5s (down from 3s).

These timers are delays. I'll toy with it tonight and see how it feels and how the game responds.

**Comment by Saaappi** [comment]
Changed in 35e6e80, then again in 2f0741b.
