### ISSUE TITLE
Error message pops up with chat options

### ISSUE THREAD

**Issue by TiaMarieG** [Saaappi/HelpMePlay#65]
8x HelpMePlay/Automations/Gossip.lua:48: attempt to index local 'gossipTable' (a nil value)
[string "@HelpMePlay/Automations/Gossip.lua"]:48: in function <HelpMePlay/Automations/Gossip.lua:36>
[string "@HelpMePlay/Automations/Gossip.lua"]:213: in function <HelpMePlay/Automations/Gossip.lua:199>
[string "@HelpMePlay/Automations/Gossip.lua"]:249: in function <HelpMePlay/Automations/Gossip.lua:236>
[string "@HelpMePlay/Automations/Gossip.lua"]:239: in function <HelpMePlay/Automations/Gossip.lua:238>

Locals:
options = <table> {
}
npcId = 27856
parentMapID = 113
gossipTable = nil
(*temporary) = 113
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = 0
(*temporary) = 1
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index local 'gossipTable' (a nil value)"
GetGossipTable = <function> defined @HelpMePlay/Automations/Gossip.lua:18

**Comment by Saaappi** [comment]
Added a check for "nilness" to the _gossipTable_ variable in 80c0fd7.
