### ISSUE TITLE
Soulbound Mode Suggestion

### ISSUE THREAD

**Issue by Elloran711** [Saaappi/HelpMePlay#68]
Hello, 
First, thanks for the addon, it's awesome!! One suggestion I do have is for the Auto Sell feature, mainly the Soulbound Mode. I would love to use this feature, but I have a Cloak of Coordination that is ilvl 29 in my inventory that I would like to keep, but the current Soulbound Mode sells it. I would suggest a feature to block certain items from being sold. 

Thank you.

**Comment by Saaappi** [comment]
Hi @Elloran711, 

You can blacklist the cloak to prevent it from being sold by Junker.

You can do this with a keybind if you set one or enter _/hmp junker blacklist_ and paste the item. If done correctly, you'll see blacklisted text in the item's tooltip.
