### ISSUE TITLE
Threads of Fate opt-in not working

### ISSUE THREAD

**Issue by KrakenLatte** [Saaappi/HelpMePlay#74]
Threads of Fate (while not available <60) still requires you choose it and type in FATE if you enter SL on a fresh 60. The automation for it does not seem to be working.

**Comment by Saaappi** [comment]
Hi,

For stuff like this, I need to know exactly _where_ it doesn't work. When you speak with Roh-Tahl, does it select Threads of Fate, but then hangs on the popup? Does it not choose the Threads of Fate button at all?

**Comment by Saaappi** [comment]
This is resolved.
