### ISSUE TITLE
Talant learning error

### ISSUE THREAD

**Issue by dgnzls77** [Saaappi/HelpMePlay#78]
I'm trying to use the talent "Learn" feature, but it doesn't seem to work for me on any of my characters.

I import the import string; I can see in the HelpMePlay. lua that it imported correctly. However, when I click in the "Learn" button on the UI, it always gives me the "Error: The loadout you are trying to import was saved from an old version" error. As if the import string is wrong, but it's not.

It's really not a huge deal but was wondering if there was a fix for that.

**Comment by Saaappi** [comment]
This is fixed in the first 3.0.0 beta build, slated to release on or before the next patch.
