### ISSUE TITLE
Incorrect dialog selection during Reinforcements for Loch Modan

### ISSUE THREAD

**Issue by seracid** [Saaappi/HelpMePlay#8]
**HMP Version**: 1.1.8d

**Quest**: Reinforcements for Loch Modan (id: 26131)
**NPC with dialog**: Gryth Thurden

**Description of bug**:
NPC is also the flightmaster and HMP immediately skips to the flight map instead of selecting the dialog for the free flight (which is second option).

**Comment by Saaappi** [comment]
Fixed in c163d73.
