### ISSUE TITLE
Repeatable Quests Can Be a Problem!

### ISSUE THREAD

**Issue by KrakenLatte** [Saaappi/HelpMePlay#81]
Requesting an option to toggle "repeatable" turn-in quests! These are usually the only ones that I've found will cause a problem (like taking items I don't want to lose), BUT I do like the auto turnin for them when I want it! 
They're so bad when I don't though!

**Comment by Saaappi** [comment]
Implemented in [3.0.0B2](https://www.curseforge.com/wow/addons/helpmeplay/files/5318781).
