### ISSUE TITLE
Requesting ExpBuddy be updated

### ISSUE THREAD

**Issue by KrakenLatte** [Saaappi/HelpMePlay#82]
Requesting that the addon ExpBuddy be updated! 
It tracked xp by source, so mobs, quests, zone exploration, nodes (herbs/ore/treasures), and rested XP, all by zone (including zone name that auto changed between zones).

It doesn't need to be changed, just updated so it works again. This would be SUPER useful for the next expansion since I am going to redo ALL the zones for my zone catalog and add in what this addon can track! 

Please and thank youuu! <3

![image](https://github.com/Saaappi/HelpMePlay/assets/89053383/e4ae263a-13b4-48aa-ad82-64373ef78746)

**Comment by Saaappi** [comment]
https://www.curseforge.com/wow/addons/expbuddy/files/5333706
