### ISSUE TITLE
World Event Queue button not usable when Dragonriding

### ISSUE THREAD

**Issue by nhtwolf** [Saaappi/HelpMePlay#84]
Not sure how difficult it is to make a button movable and it's a reletaviely minor annoyance since you can just get off the dragon but when Dragonriding the Vigor bars are on top of the World Event Queue button. Also if using a UI with a top bar it partially covers it up but when not on a dragon it's still usable. 

![image](https://github.com/Saaappi/HelpMePlay/assets/99930326/80b5a9b8-ee5e-4aa0-b92a-307ddb6fd1d7)

**Comment by Saaappi** [comment]
I don't play with anything other than the TomTom arrow at the top of my screen. It didn't occur to me the button should be movable. I already put B8.3 out (just uploaded to CF today).

I'll fix this in B8.4.

**Comment by Saaappi** [comment]
Changed in 0eea33f.
