### ISSUE TITLE
Can You Please Re-Add the Custom Dialog Feature?

### ISSUE THREAD

**Issue by KrakenLatte** [Saaappi/HelpMePlay#88]
Can You Please Re-Add the Custom Dialog Feature old HMP had? This is the one that used the /hmp dialog command when targeting specific NPCs with the options open and could then set it to always choose one. I used this feature daily/constantly and already feel it's absence since the ones I had are gone! Pretty please? <3

**Comment by Saaappi** [comment]
![image](https://github.com/user-attachments/assets/a37896c9-348e-4609-86f2-11c624016f06)

This has been implemented in ac8b024.
