### ISSUE TITLE
Double deposit/withdrawal of gold to/from warband bank

### ISSUE THREAD

**Issue by Amethice** [Saaappi/HelpMePlay#89]
**Issue Description:** 

Every time I open the bank, it does the automatic withdrawal/deposit twice.

Started noticing this today. I had automatic gold deposits set to keep me at 1000g without the "keep me safe" checkbox. My AH alt had about 18k gold, I opened the bank. It first deposited the right amount, and then immediately gave me a "I don't have that much" type error (the chat still showed the "Deposited 17601(G)74(S)2(C)" message, twice. I then changed the limit to 500g (I had done this on my main wow account, but not this one) and opened the bank again. It deposited 500 twice, bringing me to 0. I close the bank and reopen, and it withdraws twice, bringing me to 1000 again. I manually deposit 200 (bringing me to 800) and open the bank, it deposits 300 twice, bringing me to 200. I change the limit to 300 and open, it withdraws 100 twice to 400 (I did the last to make sure it wasn't some other addon I didn't know about). Activating the "Keep me Safe" checkbox will result in it only doing the withdrawal/deposit once, after you click "Yes".

**Steps to Reproduce:** 

Open bank with auto-deposits turned on and a value different from what you have. Observe the deposit/withdrawal happens twice for the "correct" amount.

**Expected Behavior:** 

When the bank is opened and the Warband Bank "Deposit Keep Amount" is set but "Keep Me Safe" isn't, it automatically withdraws or deposits the correct amount once, bringing you to the desired gold total.

**Actual Behavior:** 

When the bank is opened and the Warband Bank "Deposit Keep Amount" is set but "Keep Me Safe" isn't, it automatically withdraws or deposits the correct amount twice, making you over- or undershoot the desired gold total.

**Additional Information:**  

Issue occurs on the 3.0.4H1 version, which is the latest released version at the time this bug ticket is created.
![HMP-double-gold-transfer](https://github.com/user-attachments/assets/0416638a-6132-41c5-8146-428c9b8241d3)

**Comment by Saaappi** [comment]
Fixed in 07ba1ea.
