### ISSUE TITLE
Quest 'The MOTHERLODE!!: Raw Deal' not automatically skipped over

### ISSUE THREAD

**Issue by seracid** [Saaappi/HelpMePlay#9]
**Description**: When going to get the Drustvar foothold quest from Gallywix, HMP does not skip the quest with an unskippable RP scene that prevents selection of the correct quest.

**Quest Name (ID) to skip**: 
- _The MOTHERLODE!!: Raw Deal_ (53437) (this is first dialog choice)

**Quest Name (ID) to accept**:
- _Drustvar Ho!_ (51340) (when quest is available, this is second choice)

**Comment by Saaappi** [comment]
Fixed in ea171db.
