### ISSUE TITLE
Warband Bank's Deposit Keep Amount is in Copper

### ISSUE THREAD

**Issue by Amethice** [Saaappi/HelpMePlay#90]
Noticed today (when converting a char from Remix to Retail) that the Deposit Keep Amount (which slider goes from 0 to 1000) seems to be in copper - when I had it set to 100 it kept 1 silver, and maxing it out at 1000 means it kept 10 silver. I also noticed that the value before I touched the slider had several more zeroes, so that was probably my previous 100 gold limit being shown as 1000000.

Addon Version: 3.0.4H4

**Comment by Saaappi** [comment]
Please let me know if this is still an issue in 3.1.0.

Thank you!

@Amethice

**Comment by Amethice** [comment]
Looking all good now. Consider the fix confirmed on my end.
