### ISSUE TITLE
Categorize Mounts

### ISSUE THREAD

**Issue by TRAMAduck** [Saaappi/HelpMePlay#91]
Get error when using categorize mounts.

![image](https://github.com/user-attachments/assets/3a675188-c7b5-45ea-97ae-8317b3a69aae)

**Comment by Saaappi** [comment]
Thank you. I will add these today. Since it is a priority 3, it will be implemented with the release of version 3.1.1 on September 10.

**Comment by Saaappi** [comment]
This has been addressed with 7c9156e.
