### ISSUE TITLE
Heal battlepet button not working

### ISSUE THREAD

**Issue by nhtwolf** [Saaappi/HelpMePlay#92]
GetSpellCooldown changed in 11.0.2 and  now returns a table instead of values so line 52 in Bandage.lua needs changed from
					local cooldown = select(2, GetSpellCooldown(reviveSpellID))
to
					local spellCooldownInfo = C_Spell.GetSpellCooldown(reviveSpellID)
					local cooldown = spellCooldownInfo and spellCooldownInfo.duration or 0
or similar :).

**Comment by Saaappi** [comment]
This is fixed in the next update. Thanks for the report!
