### ISSUE TITLE
Suggestion: Lock HMP button location

### ISSUE THREAD

**Issue by Amethice** [Saaappi/HelpMePlay#96]
The new movable HMP button caught me a little off guard, but I got it moved back to where I wanted it.

However, it feels like it'd be super easy to accidentally move it out of position - would it be possible to get options to a) specify the location numerically (for those who are super picky about getting it right on the pixel) and b) get a checkbox in the option to lock the position so you don't accidentally drag it out of position?

**Comment by Pairaka** [comment]
Or perhaps disable it entirely.

**Comment by Saaappi** [comment]
If it caught you off guard, then you're not reading the change notes.

The purpose of moving it to the center of the screen is because I knew people would try to move it, and realize they can now.

I'll add a setting to lock the button's position.

**Comment by Saaappi** [comment]
> Or perhaps disable it entirely. 

Please open a separate enhancement request if you want the option to disable it.

**Comment by Saaappi** [comment]
Implemented in ef3d255.

![LockMicroMenuButton](https://github.com/user-attachments/assets/ee215d74-4405-486a-a281-10e12936a4a8)
