### ISSUE TITLE
Suggestion: Add character blacklist to WarbandBank Auto Deposit

### ISSUE THREAD

**Issue by RyzackTech** [Saaappi/HelpMePlay#97]
So I love the warband bank auto deposit feature. However, I was wondering if a character blacklist can be added to not run on certain characters OR an addon profile so I can change it for my main only. Thanks :) 

Also, can the amount be increased? 

Love the addon, thanks in advance.

**Comment by Saaappi** [comment]
I'll think about the "blacklist". Adding profiles for only one feature in the addon won't happen.

As for increasing the amount, what are you thinking as to what the new cap would be?

**Comment by RyzackTech** [comment]
Maybe 10k gold? Thanks :)

**Comment by Saaappi** [comment]
Increased the slider count from 1,000 to 10,000 in e57d702. This will go live on Oct 22.
