### ISSUE TITLE
[BUG] EvaluateCondition error

### ISSUE THREAD

**Issue by nhtwolf** [Saaappi/HelpMePlay#98]
When speaking to Gnawbles (The Ringing Deeps: Gundargaz 47.69, 35.28) I receive the below error. I am on the quest "Everyday I'm Snufflin'" (ID:79343) and have completed the first objective of turning in the Odd Glob of Wax.

9x HelpMePlay/_Functions/EvaluateConditions.lua:82: attempt to index field '?' (a nil value)
[string "@HelpMePlay/_Functions/EvaluateConditions.lua"]:82: in function `EvaluateConditions'
[string "@HelpMePlay/Gossip/Gossip.lua"]:40: in function <HelpMePlay/Gossip/Gossip.lua:29>
[string "@HelpMePlay/Gossip/Gossip.lua"]:215: in function <HelpMePlay/Gossip/Gossip.lua:84>

Locals:
conditions = <table> {
 1 = <table> {
 }
 2 = <table> {
 }
}
numConditions = 1
(for state) = <table> {
 1 = <table> {
 }
 2 = <table> {
 }
}
(for control) = 2
_ = 2
condition = <table> {
 1 = "QUEST_OBJECTIVES_INCOMPLETE"
 2 = <table> {
 }
}
cond = "QUEST_OBJECTIVES_INCOMPLETE"
quests = <table> {
 1 = <table> {
 }
}
numQuests = 1
(for state) = <table> {
 1 = <table> {
 }
}
(for control) = 1
_ = 1
quest = <table> {
 1 = 79343
 2 = 3
}
questId = 79343
objectiveIndex = 3
objectives = <table> {
 1 = <table> {
 }
}
(*temporary) = nil
(*temporary) = 79343
(*temporary) = <table> {
 1 = <table> {
 }
}
(*temporary) = 1
(*temporary) = "attempt to index field '?' (a nil value)"
HelpMePlay = <table> {
 Constants = <table> {
 }
 anchorMapping = <table> {
 }
 playerMapName = "The Ringing Deeps"
 SettingsCategory = <table> {
 }
 Strings = <table> {
 }
 playerClassID = 2
 playerSpecName = "Retribution"
 SpecialMaps = <table> {
 }
 CanDualWield = <table> {
 }
 playerFactionID = 1
 AdventureMaps = <table> {
 }
 playerMapID = 2214
 playerName = "Ariannasky"
 playerClassColor = <table> {
 }
 QUEST_REWARDS_TYPES = <table> {
 }
 NoCutsceneSkipMaps = <table> {
 }
 playerLevel = 80
 playerClassName = "Paladin"
 CHROMIE_TIME_IDS = <table> {
 }
 SettingsCategoryID = 42
 InventoryType = <table> {
 }
 Tooltips = <table> {
 }
 MountTypes = <table> {
 }
 QUEST_MOBS_ICON_TYPES = <table> {
 }
 classButtons = <table> {
 }
 specEditBoxes = <table> {
 }
 playerSpecID = 70
 playerClassFileName = "PALADIN"
 GenericTalentsFrame = <table> {
 }
 QUEST_MOBS_POSITION_TYPES = <table> {
 }
 EquipLoc = <table> {
 }
 SettingsLayout = <table> {
 }
 ErrorMessages = <table> {
 }
 playerGUID = "Player-57-0B0F5A88"
}

**Comment by nhtwolf** [comment]
Issue seems to have resolved itself and quest completed. Closing as it may have been a fluke or mod conflict.

**Comment by Saaappi** [comment]
Should be addressed in ab7ac12. I'll test it soon.

**Comment by Saaappi** [comment]
I tested Gnawbles last night and didn't receive a Lua error during interaction. I'm marking resolved.
