### ISSUE TITLE
Bug: Always Compare Items doesn't work without alwaysCompareItems = 1

### ISSUE THREAD

**Issue by possum-enjoyer** [Saaappi/HelpMePlay#99]
The Setting "Always Compare Items" currently does not work without first setting the cvar alwaysCompareItems to 1.

After turning the cvar on the setting does work again. 
Maybe blizzard fixed their stuff around the cvar so the hook: https://github.com/Saaappi/HelpMePlay/blob/c2a57764f50e55df29709eecd0440e5182ddea1a/Core.lua#L97

isn't needed anymore and the cvar can be toggled on or off? 

Edit: 

Also the description 

> By default, Blizzard displays the comparison tooltip when hovering over any equippable item. To toggle this functionality, uncheck this button.

might be misleading? the cvar value responsible is off by default.

**Comment by Saaappi** [comment]
Thanks for your report. I tested the cvar and it would appear Blizzard fixed it; I removed the code on my side in the 3.2.2 update (released today).
